import db from "../config/db.js";
import { uploadToS3 } from "../services/s3Service.js";
import { assignDepartment } from "../services/assignmentService.js";
import { sendNotification } from "../services/notificationService.js";

/**
 * POST /api/complaints
 * Creates a new complaint, uploads photos to S3, assigns department & officer.
 */
export const createComplaint = async (req, res, next) => {
  const client = await db.connect();
  try {
    await client.query("BEGIN");

    const {
      category,
      title,
      description,
      severity = 2,
      latitude,
      longitude,
      address_text = "",
    } = req.body;

    // Basic validation
    if (!category || !title || !description || !latitude || !longitude) {
      return res.status(400).json({ message: "Missing required fields" });
    }

    // userId is an INTEGER from SERIAL PRIMARY KEY (not a UUID)
    const userId = req.user?.id && req.user.id !== 0 ? req.user.id : null;

    let wardId = null;

    // 1. Determine ward from coordinates
    // Try getting ward based on user's municipal_id
    if (userId) {
      try {
        const userResult = await client.query(`SELECT municipal_id FROM users WHERE id = $1`, [userId]);
        if (userResult.rows[0]?.municipal_id) {
          const wardResult = await client.query(
            `SELECT id FROM wards WHERE municipal_id = $1 LIMIT 1`,
            [userResult.rows[0].municipal_id]
          );
          wardId = wardResult.rows[0]?.id;
        }
      } catch (err) {
        console.log("Ward fetch from user failed:", err.message);
      }
    }

    // Fall back to first available ward
    if (!wardId) {
      const fallbackWard = await client.query(`SELECT id FROM wards LIMIT 1`);
      wardId = fallbackWard.rows[0]?.id;
    }

    if (!wardId) {
      await client.query("ROLLBACK");
      return res.status(422).json({ message: "Could not determine ward. Please contact support." });
    }

    // 2. Find matching department
    let department = await assignDepartment(wardId, category, client);
    // If no department found for this category, try ANY department as last resort
    if (!department) {
      const anyDept = await client.query(`SELECT id, name, contact_phone FROM departments LIMIT 1`);
      department = anyDept.rows[0] || null;
    }
    if (!department) {
      await client.query("ROLLBACK");
      return res.status(422).json({ message: "No department configured yet. Please contact admin." });
    }

    // 3. Insert complaint (complaint_no auto-generated by trigger)
    const { rows } = await client.query(
      `INSERT INTO complaints
         (user_id, category, ward_id, department_id, title, description, severity, latitude, longitude, address_text, status)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'submitted')
       RETURNING id, complaint_no`,
      [userId, category, wardId, department.id, title, description, severity, latitude, longitude, address_text]
    );
    const complaint = rows[0];

    // 4. Insert initial timeline event
    await client.query(
      `INSERT INTO timeline_events (complaint_id, status, actor_type, note)
       VALUES ($1, 'submitted', 'citizen', 'Complaint registered by citizen')`,
      [complaint.id]
    );

    // 5. Upload photos to S3 (if any)
    if (req.files?.length > 0) {
      for (const file of req.files) {
        const s3Key = `complaints/${complaint.id}/${Date.now()}-${file.originalname}`;
        await uploadToS3(file.buffer, s3Key, file.mimetype);
        await client.query(
          `INSERT INTO media (complaint_id, s3_key, s3_bucket, mime_type, size_bytes)
           VALUES ($1, $2, $3, $4, $5)`,
          [complaint.id, s3Key, process.env.S3_BUCKET || 'test-bucket', file.mimetype, file.size]
        );
      }
    }

    // 6. Auto-assign available officer
    const officer = await autoAssignOfficer(department.id, complaint.id, client);

    await client.query("COMMIT");

    // 7. Send SMS confirmation (non-blocking)
    sendNotification({
      userId,
      complaintId: complaint.id,
      channel: "sms",
      message: `Your complaint ${complaint.complaint_no} has been registered. Track at: [portal-url]/track/${complaint.id}`,
    }).catch(console.error);

    return res.status(201).json({
      id: complaint.id,
      complaint_no: complaint.complaint_no,
      department_name: department.name,
      assigned_officer: officer?.name || null,
      sla_days: getSLADays(category, Number(severity)),
      status: "submitted",
    });
  } catch (err) {
    if (client) await client.query("ROLLBACK");
    next(err);
  } finally {
    if (client) client.release();
  }
};

/**
 * GET /api/complaints/mine
 */
export const getMyComplaints = async (req, res, next) => {
  try {
    const userId = req.user?.id;
    if (!userId) return res.status(401).json({ message: "Not authenticated" });
    const { rows } = await db.query(
      `SELECT
         c.id, c.complaint_no, c.category, c.title, c.status,
         c.severity, c.address_text, c.created_at, c.resolved_at,
         d.name AS department_name,
         o.name AS officer_name,
         (SELECT s3_key FROM media WHERE complaint_id = c.id LIMIT 1) AS thumb_key
       FROM complaints c
       LEFT JOIN departments d ON d.id = c.department_id
       LEFT JOIN officers o ON o.id = c.assigned_officer_id
       WHERE c.user_id = $1
       ORDER BY c.created_at DESC`,
      [userId]
    );
    return res.json(rows);
  } catch (err) {
    next(err);
  }
};

/**
 * GET /api/complaints/:id
 */
export const getComplaintById = async (req, res, next) => {
  try {
    const { id } = req.params;
    const userId = req.user?.id;

    // Fetch complaint — allow admin to view any, citizen sees own
    const { rows } = await db.query(
      `SELECT
         c.*,
         d.name AS department_name, d.contact_phone AS dept_phone,
         o.name AS officer_name, o.phone AS officer_phone,
         w.name AS ward_name
       FROM complaints c
       LEFT JOIN departments d ON d.id = c.department_id
       LEFT JOIN officers o ON o.id = c.assigned_officer_id
       LEFT JOIN wards w ON w.id = c.ward_id
       WHERE c.id = $1 AND (c.user_id = $2 OR $3 = 'admin')`,
      [id, userId, req.user?.role || '']
    );

    if (!rows[0]) return res.status(404).json({ message: "Complaint not found" });
    const complaint = rows[0];

    // Fetch timeline
    const { rows: timeline } = await db.query(
      `SELECT id, status, actor_type, note, created_at
       FROM timeline_events
       WHERE complaint_id = $1
       ORDER BY created_at ASC`,
      [id]
    );

    // Fetch media keys
    const { rows: media } = await db.query(
      `SELECT id, s3_key, mime_type FROM media WHERE complaint_id = $1`,
      [id]
    );

    return res.json({ complaint, timeline, media });
  } catch (err) {
    next(err);
  }
};

/**
 * PATCH /api/complaints/:id/status
 */
export const updateStatus = async (req, res, next) => {
  const client = await db.connect();
  try {
    await client.query("BEGIN");
    const { id } = req.params;
    const { status, note } = req.body;

    const VALID = ["acknowledged", "assigned", "in_progress", "resolved", "closed", "rejected"];
    if (!VALID.includes(status)) {
      return res.status(400).json({ message: "Invalid status value" });
    }

    const userId = req.user?.id || 1;

    // Update complaint (the trigger logs the timeline_event automatically, or we log manually if no trigger defined for it)
    await client.query(
      `UPDATE complaints SET status = CAST($1 AS VARCHAR),
         acknowledged_at = CASE WHEN CAST($1 AS VARCHAR) = 'acknowledged' THEN NOW() ELSE acknowledged_at END,
         assigned_at     = CASE WHEN CAST($1 AS VARCHAR) = 'assigned'     THEN NOW() ELSE assigned_at END,
         resolved_at     = CASE WHEN CAST($1 AS VARCHAR) = 'resolved'     THEN NOW() ELSE resolved_at END,
         closed_at       = CASE WHEN CAST($1 AS VARCHAR) = 'closed'       THEN NOW() ELSE closed_at END,
         resolution_note = COALESCE(CAST($3 AS TEXT), resolution_note)
       WHERE id = $2`,
      [status, id, note || null]
    );

    // Override the system timeline event note with the officer's note
    if (note) {
      await client.query(
        `UPDATE timeline_events
         SET note = $1, actor_type = 'officer', actor_id = $2
         WHERE id = (
           SELECT id FROM timeline_events 
           WHERE complaint_id = $3 AND status = $4
           ORDER BY created_at DESC 
           LIMIT 1
         )`,
        [note, userId, id, status]
      );
    }

    await client.query("COMMIT");

    // Notify citizen
    const { rows } = await db.query(
      `SELECT u.id AS user_id, c.complaint_no FROM complaints c JOIN users u ON u.id = c.user_id WHERE c.id = $1`,
      [id]
    );
    if (rows[0]) {
      sendNotification({
        userId: rows[0].user_id,
        complaintId: id,
        channel: "sms",
        message: `Update on ${rows[0].complaint_no}: Status changed to "${status}". ${note || ""}`,
      }).catch(console.error);
    }

    return res.json({ success: true, status });
  } catch (err) {
    if (client) await client.query("ROLLBACK");
    next(err);
  } finally {
    if (client) client.release();
  }
};

// ─── Helpers ────────────────────────────────────────────────────

async function autoAssignOfficer(departmentId, complaintId, client) {
  // Assign officer with fewest active complaints in this department
  const { rows } = await client.query(
    `SELECT o.id, o.name
     FROM officers o
     LEFT JOIN complaints c ON c.assigned_officer_id = o.id
       AND c.status NOT IN ('resolved','closed','rejected')
     WHERE o.department_id = $1 AND o.is_available = TRUE
     GROUP BY o.id, o.name
     ORDER BY COUNT(c.id) ASC
     LIMIT 1`,
    [departmentId]
  );

  if (!rows[0]) return null;

  await client.query(
    `UPDATE complaints SET assigned_officer_id = $1, assigned_at = NOW(), status = 'assigned'
     WHERE id = $2`,
    [rows[0].id, complaintId]
  );

  await client.query(
    `INSERT INTO timeline_events (complaint_id, status, actor_type, actor_id, note)
     VALUES ($1, 'assigned', 'system', $2, $3)`,
    [complaintId, rows[0].id, `Assigned to ${rows[0].name}`]
  );

  return rows[0];
}

function getSLADays(category, severity) {
  const base = { water: 3, electricity: 2, hospital: 2, hygiene: 3, tax: 7, public_transport: 5, roads: 7, drainage: 5, street_lights: 4, parks: 10, other: 7 };
  const days = base[category] || 7;
  if (severity >= 4) return Math.max(1, Math.floor(days / 2));
  return days;
}

/**
 * GET /api/complaints/all
 * Admin route to get all complaints with user info.
 */
export const getAllComplaints = async (req, res, next) => {
  try {
    const { rows } = await db.query(
      `SELECT
         c.id, c.complaint_no, c.category, c.title, c.description, c.status,
         c.severity, c.address_text, c.created_at, c.resolved_at,
         d.name AS department_name,
         o.name AS officer_name,
         u.name AS user_name, u.mobile AS user_mobile
       FROM complaints c
       LEFT JOIN departments d ON d.id = c.department_id
       LEFT JOIN officers o ON o.id = c.assigned_officer_id
       LEFT JOIN users u ON u.id = c.user_id
       ORDER BY c.created_at DESC`
    );
    return res.json(rows);
  } catch (err) {
    next(err);
  }
};
